# [workspace]
# members = ["smtlib"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[package]
name = "ssapper"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smtlib = { path = "./smtlib" }
peg = "0.8.1"
rayon = "1.9.0"
colored = "2.1.0"
