# [workspace]
# members = ["smtlib"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[package]
name = "smtprof"
version.workspace = true
version.edition = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smtlib = { path = "./smtlib" }